### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by dmcg89** [Jeromeschmidt/Herd-Immunity-Simulation#1]
-  The visualization was very well done
-  The test coverage for Person Class was not quite as extensive as the rubric prompted (having 5+ tests for person and some tests for simulation)
-  Good job going above and beyond and testing the logging class
-  All in well, very well done!

**Comment by Jeromeschmidt** [comment]
Thanks for the awesome feedback, I'll be sure to improve on the test coverage!
